SET IDENTITY_INSERT [dbo].[Table] ON
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (86, N'Açık Kapı           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (135, N'Adım                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (85, N'Ağlamak             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (81, N'Alışkanlık          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (82, N'Alışveriş           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (171, N'Alışveriş           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (13, N'Ankara              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (1, N'Armut               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (117, N'Aşk                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (107, N'Avaz Avaz           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (115, N'Ayakkabı            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (93, N'Ayrı Gayrı          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (131, N'Bahşiş              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (75, N'Balkon              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (150, N'Başarı              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (43, N'Başlamak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (133, N'Başvurmak           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (15, N'Batı                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (14, N'Batıkent            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (132, N'Bayram              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (77, N'Bebek               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (22, N'Beklemek            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (111, N'Beklemek            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (42, N'Bilememek           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (5, N'Bilgili             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (113, N'Bilmek              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (147, N'Birlik              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (44, N'Bitirmek            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (97, N'Boşluk              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (76, N'Çakışmak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (45, N'Çakmak              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (108, N'Cancağız            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (16, N'Çatı                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (146, N'Çay                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (3, N'Çelişki             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (80, N'Çıkarmak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (74, N'Çıkışmak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (165, N'Cilt                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (170, N'Çıtır               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (141, N'Çorba               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (144, N'Cürret Etmek        ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (125, N'Dans Etmek          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (159, N'Davlumbaz           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (124, N'Dedikodu            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (54, N'Defne               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (87, N'Derin Kuyu          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (106, N'Derya               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (32, N'Doğramak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (130, N'Doğru               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (134, N'Dondurma            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (110, N'Düşünce             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (55, N'Duyamamak           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (105, N'Ecel                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (127, N'Ekonomi             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (49, N'Elçi                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (2, N'Elma                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (39, N'Emin Olmak          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (90, N'Endişe              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (163, N'Etki                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (167, N'Etkili              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (119, N'Evli Barklı         ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (149, N'Geçmiş              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (101, N'Gelecek             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (91, N'Gezgin              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (103, N'Gıybet              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (4, N'Gölgelik            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (7, N'Göreceli            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (73, N'Göstermek           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (84, N'Gözde               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (95, N'Gözlem              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (6, N'Gün Saymak          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (67, N'Güzellik            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (109, N'Hatıra              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (114, N'Havadis             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (68, N'Hayal               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (69, N'Herşey              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (121, N'Hilal               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (8, N'Huy                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (57, N'Huysuz              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (50, N'İçeriden            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (48, N'İlan                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (24, N'İnanç               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (34, N'İnanmamak           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (38, N'İşbaşı              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (94, N'Ispatlamak          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (66, N'İstikbal            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (10, N'Kaba                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (28, N'Kahve               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (156, N'Kalite              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (25, N'Kalmak              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (136, N'Kalp                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (56, N'Kandırmak           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (53, N'Kaplan              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (12, N'Kara Kutu           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (17, N'Kat                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (26, N'Katmak              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (36, N'Kayıp               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (129, N'Keyif               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (59, N'Kirli Hava          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (61, N'Kıvılcım            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (70, N'Kıymetli            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (33, N'Kokteyl             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (78, N'Komik               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (37, N'Konak               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (118, N'Kumru               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (11, N'Kuyu                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (153, N'Lezzet              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (172, N'Macera              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (99, N'Makarna             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (164, N'Makyaj              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (65, N'Mecal               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (102, N'Mevsim              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (51, N'Miras               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (79, N'Mobilya             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (100, N'Mücevher            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (104, N'Mucize              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (158, N'Mutfak              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (9, N'Nafile              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (138, N'Nefes               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (152, N'Neşe                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (126, N'Nikah               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (122, N'Oda                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (88, N'Okyanus             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (120, N'Olan Biten          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (160, N'Peşin               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (169, N'Pide                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (89, N'Rahatlık            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (123, N'Restorant           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (60, N'Şans                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (23, N'Şaşırmak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (29, N'Sehpa               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (31, N'Şerbetli            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (143, N'Serinlik            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (52, N'Sezon               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (168, N'Sıcak               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (145, N'Şifre               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (46, N'Şikayet             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (20, N'Sınır               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (19, N'Sinirli             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (116, N'Sıra                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (96, N'Sitem               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (137, N'Sofra               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (30, N'Soğuk               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (72, N'Şok Olmak           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (112, N'Susmak              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (166, N'Tahriş              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (27, N'Tansiyon            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (157, N'Tasarım             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (142, N'Tat                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (162, N'Teknoloji           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (58, N'Temiz Hava          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (140, N'Terbiyeli Tavuk     ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (83, N'Terk Etmek          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (64, N'Toprak              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (62, N'Torun               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (63, N'Tosun               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (21, N'Ukte                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (151, N'Ülke                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (41, N'Unutmak             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (35, N'Uzaklaşmak          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (155, N'Vücut               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (71, N'Yadigar             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (128, N'Yalıtım             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (92, N'Yaraşmak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (161, N'Yaşam               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (18, N'Yat                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (40, N'Yetimhane           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (148, N'Yıldız              ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (139, N'Yöresel             ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (98, N'Yorulmak            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (154, N'Yüz                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (47, N'Zeval               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (173, N'Töre                ', NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [Kelime], [Anlam], [Ekli], [Bildi]) VALUES (174, N'Desteklemek         ', NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Table] OFF
